version: '3'

services:
    web:
        build:
            context: .
        ports:
            - "8080:80"
        depends_on:
            - db
    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: mlstore
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        
volumes:
    db_data:
